### ISSUE TITLE
Trap Focus does not update tabbableChildren on children update

### ISSUE THREAD

**Issue by JulienPradet** [reecelucas/svelte-accessible-dialog#17]
Hi!

First of all, thanks for putting this library together. It's nice to have the a11y features and its API works like a charm. :)

However I ran into an issue with the TrapFocus component. If the component that I display within creates new focusable elements along the way (and not onMount), the `tabbableChildren` variable within `TrapFocus.svelte` is not updated.
This can be tested by creating inside the ModalContent a button that only appears after a checkbox is checked. If the activeElement is the checkbox, you will never be able to tab to the new button. (My use case is actually some component lazyloading.)

A common solution I use for this is to get the focusable elements during the keydown event instead. And in order to avoid too much of a slowdown because of the `querySelectorAll('*').filter(...)`, I rely on this selector instead.

```
// source: https://github.com/nico3333fr/van11y-accessible-modal-window-aria/blob/master/src/van11y-accessible-modal-window-aria.es6.js#L41
const FOCUSABLE_ELEMENTS_STRING = "a[href], area[href], input:not([type='hidden']):not([disabled]), select:not([disabled]), textarea:not([disabled]), button:not([disabled]), iframe, object, embed, *[tabindex], *[contenteditable]";
```

Would this fix be something you'd consider if I put together a PR?

**Comment by reecelucas** [comment]
@JulienPradet absolutely, this sounds very sensible. It's a clear use case that I should have anticipated earlier 🤦 That string looks promising, although perhaps `[tabindex]:not([tabindex="-1"])` would be preferable to `*[tabindex]` 😄
